site_name: NeuroNexo Tec

nav:
  - Home: index.md
  - Inicio:
    - Acerca de nosotros: ./comunidad/nosotros.md
    - Como puedes participar: ./comunidad/como-participar.md
    - Licencia: ./comunidad/licencia.md
  - Desarrollo:
    - Manejador de errores:
      - Introduccion: ./desarrollo/error-handler/introduccion.md
      - Capas de implementacion: ./desarrollo/error-handler/capas.md
      - Modelos estándar: ./desarrollo/error-handler/modelo-estandar.md
      - Clasificación de errores: ./desarrollo/error-handler/clasificacion-errores.md
      - Captura y propagación: ./desarrollo/error-handler/captura-propagacion.md
      - Centralizacion de captura: ./desarrollo/error-handler/centralizacion-captura.md
      - Resilencia y recupercaión: ./desarrollo/error-handler/resilencia-recupercaion.md
      - Seguridad y sanitización: ./desarrollo/error-handler/seguridad-sanitizacion.md
      - Monitoreo: ./desarrollo/error-handler/monitoreo.md
      - SDK's: 
        - Java: ./desarrollo/error-handler/sdk/java.md
        - PHP: ./desarrollo/error-handler/sdk/php.md
      - Glosario: ./desarrollo/error-handler/glosario.md
  - Cursos:
    - Analisis de datos: ./cursos/analisis-datos/inicio.md

theme: 
  name: material
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
  locale: es
  features:
    - navigation.instant
    - navigation.instant.prefetch
repo_url: https://github.com/example/repository/

